# Generated by Django 3.0.2 on 2020-01-05 14:51

import audit.models
from django.db import migrations, models
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='无', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('_price', models.IntegerField(default=0)),
                ('insert_time', models.IntegerField(default=1578235905)),
                ('old', models.BooleanField(default=False)),
                ('types', models.ForeignKey(default=0, on_delete=models.SET(audit.models.default_product_type), to='audit.ProductType')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_time', models.IntegerField(default=time.time)),
                ('state', models.IntegerField(choices=[(0, '未结清'), (1, '已结清')])),
                ('products', models.ManyToManyField(to='audit.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_price', models.IntegerField(default=0)),
                ('buy_time', models.IntegerField(default=time.time)),
                ('state', models.IntegerField(choices=[(0, '未结清'), (1, '已结清')])),
                ('item', models.ManyToManyField(to='audit.CostType')),
            ],
        ),
    ]
