# Generated by Django 3.0.2 on 2020-01-07 13:36

import audit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='成本类型')),
            ],
        ),
        migrations.CreateModel(
            name='CouponItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='名称')),
                ('phone', models.CharField(max_length=200, verbose_name='手机')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='无', max_length=50, verbose_name='产品类型')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='单位')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('_price', models.IntegerField(default=0, verbose_name='价格')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='插入时间')),
                ('old', models.BooleanField(default=False, verbose_name='是否旧价格')),
                ('types', models.ForeignKey(on_delete=models.SET(audit.models.default_product_type), to='audit.ProductType', verbose_name='产品类型')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0, verbose_name='订单ID')),
                ('number', models.IntegerField(default=0, verbose_name='数量')),
                ('sale_time', models.DateTimeField(auto_now_add=True, verbose_name='销售时间')),
                ('state', models.IntegerField(choices=[(0, '未结清'), (1, '已结清')], default=1)),
                ('discount', models.FloatField(default=1, verbose_name='折扣')),
                ('member', models.ForeignKey(on_delete=models.SET(audit.models.default_member), to='audit.Member', verbose_name='会员')),
                ('product', models.ForeignKey(on_delete=models.SET(audit.models.default_product), to='audit.Product', verbose_name='产品')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('exchange', models.IntegerField(default=0, verbose_name='兑换次数')),
                ('coupon', models.ForeignKey(on_delete=models.SET(audit.models.default_coupon_item), to='audit.CouponItem', verbose_name='优惠券')),
                ('user', models.ForeignKey(on_delete=models.SET(audit.models.default_member), to='audit.Member', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='名称')),
                ('number', models.FloatField(default=0, verbose_name='数量')),
                ('source', models.TextField(verbose_name='来源')),
                ('_price', models.IntegerField(default=0, verbose_name='价格')),
                ('buy_time', models.DateTimeField(auto_now_add=True, verbose_name='购买时间')),
                ('state', models.IntegerField(choices=[(0, '未结清'), (1, '已结清')], default=1, verbose_name='状态')),
                ('costtype', models.ForeignKey(on_delete=models.SET(audit.models.default_costtype), to='audit.CostType', verbose_name='成本类型')),
                ('unit', models.ForeignKey(on_delete=models.SET(audit.models.default_unit), to='audit.Unit', verbose_name='单位')),
            ],
        ),
    ]
