# Generated by Django 2.2.3 on 2020-01-06 11:50

import audit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20200106_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(to='audit.Product', verbose_name='购物车'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='数量')),
                ('product', models.ForeignKey(on_delete=models.SET(audit.models.default_product_type), to='audit.Product', verbose_name='产品')),
            ],
        ),
    ]
