# Generated by Django 2.2.9 on 2020-01-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20200108_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=200, unique=True, verbose_name='手机'),
        ),
    ]
