# Generated by Django 2.2.3 on 2020-01-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auto_20200106_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(to='audit.Item', verbose_name='购物车'),
        ),
    ]
